service: felandil-basket

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: src/handler.hello
    events:
        - http:
            path: hello
            method: get
resources:
  Resources:

package:
    exclude:
        - "node_modules/**"
